language: cpp

os:
 - linux
# - osx

compiler:
#  - clang
  - gcc

install: 
 - wget https://libav.org/releases/libav-12.3.tar.gz
 - tar -xvf libav-12.3.tar.gz
 - PATH=$PATH:/data/myscripts

script: make install
