language: cpp

os:
 - linux
# - osx

compiler:
#  - clang
  - gcc

install: 
 - wget https://libav.org/releases/libav-12.3.tar.gz
 - tar -xvf libav-12.3.tar.gz
 - cd libav-12.3
 - make
 - PATH=$PATH:$CD
 - cd ..

script: make install
